shellEmulator: true

trustPolicy: no-downgrade

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - esbuild
  - sharp

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  esbuild: true
  sharp: true
  vue-demi: true
